### ISSUE TITLE
Bind on specific IP

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [sayanriju/Tiny-Bash-Server#1]
Hi Sayan,
is there any config to bind on a specific IP?
thanks for your nice job

**Comment by sayanriju** [comment]
Short answer: As of now, nope! :=(

Long Answer: TBS delegates the networking part to `netcat`. So, by changing the options passed to `nc` while starting the server, you might get it to work.

So, put on your hacking hat, and try editing the file `usr/bin/tbs.start`, in particular lines 28 and 30. :=)

I have a feeling that `nc -l 192.168.2.1 1983` or `nc -l -p 1983 -s 192.168.2.1` may work as you want.

Patches/PRs are more than welcome!

**Comment by ROBERT-MCDOWELL** [comment]
Ok great, I'm not familiar with PR so will try it thank you very muc
